# Generated by Django 4.1.5 on 2023-01-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='platform_tax',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
